www/routes/web.php
<?php

use App\Models\Shipment;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend.index');
});

Auth::routes();

// Route::get('/mail', function () {
//     $shipment = Shipment::find(16);
//     $mailType = 'vendor';
//     return view('email.free-quote-mail', compact('shipment', 'mailType'));
// });



Route::group(['namespace' => 'App\Http\Controllers'], function () {
    Route::get('/autologin', 'Auth\LoginController@autoLogin');

    Route::match(['get', 'post'], '/logout', 'Auth\LoginController@logout')->name('logout');

    Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['role:admin']], function () {
        Route::get('/dashboard', 'DashboardController@index')->middleware('permission:dashboard_access')->name('dashboard');

        /* User Management */
        Route::get('/users', 'UserController@index')->name('user.index');
        Route::get('/user/login/{id}', 'UserController@userLogin')->name('user.login');
        Route::get('/user/logout/', 'UserController@userLogout')->name('user.logout');
        Route::get('/user/create/{id?}', 'UserController@createOrEdit')->name('user.createOrEdit');
        Route::post('/user/store/{id?}', 'UserController@store')->name('user.store');
        Route::delete('/user/{id}/destroy', 'UserController@destroy')->name('user.delete');

        /* Location Management */
        Route::get('/location', 'LocationController@index')->name('location.index');
        Route::get('/location/edit/{id?}/', 'LocationController@edit')->name('location.edit');
        Route::post('/location/store/{id?}', 'LocationController@store')->name('location.store');
        Route::get('/location/show/{id}', 'LocationController@show')->name('location.show');
        Route::post('/location/assign-user/{id?}', 'LocationController@assignUser')->name('location.assign-user');
        Route::get('/location/export', 'LocationController@export')->name('location.export');
        Route::post('/location/import', 'LocationController@import')->name('location.import');

        /* Product Management */
        Route::get('/product', 'ProductController@index')->name('product.index');
        Route::get('/product/create/{id?}', 'ProductController@create')->name('product.createOrEdit');
        Route::get('/product/show/{id}', 'ProductController@show')->name('product.show');
        Route::get('/product/export', 'ProductController@export')->name('product.export');
        Route::post('/product/import', 'ProductController@import')->name('product.import');

        /* Shipments */
        Route::get('/shipments', 'ShipmentController@index')->name('shipment.index');
        Route::get('/shipment/show/{id}', 'ShipmentController@show')->name('shipment.show');
        Route::get('/shipment/change-status', 'ShipmentController@changeStatus')->name('shipment.change-status');
        Route::post('shipments/{id}/cancel', 'ShipmentController@cancelShipment')->name('shipment.cancel');
        Route::get('shipments/export', 'ShipmentController@export')->name('shipment.export');
        Route::get('shipments/cancel-shipments', 'ShipmentController@cancelShipmentIndex')->name('shipment.cancelShipments');

        /* Payouts */
        Route::get('/payouts/{status}', 'PayoutController@index')->name('payout.index');
        Route::get('/payouts/{id}/checkout', 'PayoutController@processCheckout')->name('payout.checkout');
        Route::get('/payouts/show/{id}', 'PayoutController@show')->name('payout.show');
    });

    Route::group(['prefix' => 'vendor', 'as' => 'vendor.', 'namespace' => 'Vendor', 'middleware' => ['role:vendor']], function () {
        Route::get('/dashboard', 'DashboardController@index')->middleware('permission:dashboard_access')->name('dashboard');
        Route::get('/no-locations', 'DashboardController@noLocations')->name('no-locations');

        // Trade-Ins Management
        Route::get('trade-ins', 'ShipmentController@tradeIns')->name('shipment.trade-ins');
        Route::get('trade-ins/show/{id}/', 'ShipmentController@tradeInShow')->name('shipment.trade-ins.show');

        // Shipment Management
        Route::get('shipments', 'ShipmentController@index')->name('shipment.index');
        Route::get('shipments/show/{id}/', 'ShipmentController@show')->name('shipment.show');
        Route::get('shipments/download-label/{id}', 'ShipmentController@downloadLabel')->name('shipment.download.label');
        Route::post('shipments/group-shipments', 'ShipmentController@groupShipments')->name('shipment.group-shipments');
        Route::post('shipments/{id}/cancel', 'ShipmentController@cancelShipment')->name('shipment.cancel');


        Route::get('/location/change/{id}', 'DashboardController@changeLocation')->name('location.change');

        Route::get('/shipments/approve-process/{id}', 'ShipmentController@approveProcess')->name('shipment.approveProcess');

        Route::get('/shipment-create', 'ShipmentController@createShipment')->name('shipment.create');
    });

    Route::group(['prefix' => 'user', 'as' => 'user.', 'namespace' => 'User', 'middleware' => ['auth']], function () {
        Route::get('/dashboard', 'DashboardController@index')->middleware('permission:dashboard_access')->name('dashboard');

        //Change Password
        Route::get('/password/change', 'DashboardController@changePasswordIndex')->name('password.change.index');
        Route::post('/change-password', 'DashboardController@changePassword')->name('password.change');

        // Shipment Management
        Route::get('/shipments', 'ShipmentController@index')->name('shipment.index');
        Route::get('/shipments/show/{id}/', 'ShipmentController@show')->name('shipment.show');
    });


    Route::group(['namespace' => 'Frontend'], function () {
        Route::get('/sell-your-device', 'SellDeviceController@index')->name('sell-your-device');
        Route::get('/shipment-process', 'SellDeviceController@shippingInformation')->name('shipment-process');
        Route::get('/shipment-review', 'SellDeviceController@shipmentReview')->name('shipment-review');
        Route::post('/confirm-location', 'SellDeviceController@confirmLocation')->name('confirm-location');
        Route::get('/ship-my-item', 'SellDeviceController@shipMyItemIndex')->name('ship-my-item');
        Route::get('/print-my-label', 'SellDeviceController@printMyLabelIndex')->name('print-my-label.index');
        Route::get('/print-my-label/download', 'SellDeviceController@printMyLabel')->name('print-my-label');
        Route::get('/cart', 'SellDeviceController@cart')->name('cart');
    });

    /* Contact Us */
    Route::get('contact-us', 'ContactUsController@index')->name('contact-us');
    Route::post('contact-us/store', 'ContactUsController@store')->name('contact-us.store');
    Route::post('buy-a-device-inquiry/store', 'ContactUsController@storeInquiry')->name('buy-a-device.inquiry.store');

    /** Request a free quote & Have a qustions*/
    Route::post('corporate-recycling/form/submit', 'ContactUsController@submitQuoteForm')->name('corporate-recycling.submit');
    Route::get('corporate-recycling/thank-you', 'ContactUsController@thankYouPage')->name('corporate-recycling.thankyou');

    /* Track Shipment */
    Route::get('/track-shipment', 'FrontendController@trackShipmentForm')->name('track-shipment');

    /* Sell Iphone */
    Route::get('/sell-iphone', 'FrontendController@sellIphone')->name('sell-iphone');
});

Route::group(['namespace' => 'App\Http\Livewire\Frontend'], function () {
    Route::get('/locations', Locations::class)->name('locations');
});

/*CMS Page */
Route::get('/{slug}', 'App\Http\Controllers\FrontendController@cmsPages')->name('cms-page');

Route::get('shipment-list', function () {
    return view('frontend.shipment-list');
})->name('shipment-list');

Route::get('shipment-detail/{id?}', function () {
    return view('frontend.shipment-detail');
})->name('shipment-detail');

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

www/resources/views/layouts/admin/footer.blade.php
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6">
                <script>document.write(new Date().getFullYear())</script> © Gizmogul.
            </div>
            <div class="col-sm-6">
                <div class="text-sm-end d-none d-sm-block">
                    Design & Develop by Gizmogul
                </div>
            </div>
        </div>
    </div>
</footer>

www/resources/views/layouts/admin/head.blade.php
<head>
    <meta charset="utf-8" />
    <title>@yield('title')</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
    <meta content="Themesbrand" name="author" />
    <!-- App favicon -->
    <link rel="shortcut icon" href="{{ asset('/assets/images/logos/favicon.png') }}">

    <!-- Bootstrap Css -->
    <link href="{{ asset('/assets/css/bootstrap.min.css') }}" id="bootstrap-style" rel="stylesheet" type="text/css" />
    <!-- Icons Css -->
    <link href="{{ asset('/assets/css/icons.min.css') }}" rel="stylesheet" type="text/css" />
    <!-- App Css-->
    <link href="{{ asset('/assets/css/app.min.css') }}" id="app-style" rel="stylesheet" type="text/css" />

    @stack('styles')

    @livewireStyles
</head>

www/resources/views/layouts/admin/header.blade.php
<header id="page-topbar">
    <div class="navbar-header">
        <div class="d-flex">
            <!-- LOGO -->
            <div class="navbar-brand-box">

                <a href="{{ route('admin.dashboard') }}" class="logo logo-dark">
                    <span class="logo-sm">
                        <img src="{{ asset('/assets/images/logos/gizmogul-logo-g.png') }}" alt="" height="22">
                    </span>
                    <span class="logo-lg">
                        <img src="{{ asset('/assets/images/logos/gizmogul-logo.png') }}" alt=""
                            height="17">
                    </span>
                </a>

                <a href="index.html" class="logo logo-light">
                    <span class="logo-sm">
                        <img src="{{ asset('/assets/images/logo-light.svg') }}" alt="" height="22">
                    </span>
                    <span class="logo-lg">
                        <img src="{{ asset('/assets/images/logos/gizmogul-logo-light.png') }}" alt=""
                            height="19">
                    </span>
                </a>
            </div>

            <button type="button" class="btn btn-sm px-3 font-size-16 d-lg-none header-item waves-effect waves-light"
                data-bs-toggle="collapse" data-bs-target="#topnav-menu-content">
                <i class="fa fa-fw fa-bars"></i>
            </button>

            <!-- App Search-->
            <form class="app-search d-none d-lg-block">
                <div class="position-relative">
                    <input type="text" class="form-control" placeholder="Search...">
                    <span class="bx bx-search-alt"></span>
                </div>
            </form>
        </div>

        <div class="d-flex">

            <div class="dropdown d-inline-block d-lg-none ms-2">
                <button type="button" class="btn header-item noti-icon waves-effect" id="page-header-search-dropdown"
                    data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="mdi mdi-magnify"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-end p-0"
                    aria-labelledby="page-header-search-dropdown">

                    <form class="p-3">
                        <div class="form-group m-0">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Search ..."
                                    aria-label="Search input">

                                <button class="btn btn-primary" type="submit"><i class="mdi mdi-magnify"></i></button>s
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div class="dropdown d-none d-lg-inline-block ms-1">
                <button type="button" class="btn header-item noti-icon waves-effect" data-bs-toggle="fullscreen">
                    <i class="bx bx-fullscreen"></i>
                </button>
            </div>

            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item noti-icon waves-effect"
                    id="page-header-notifications-dropdown" data-bs-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false">
                    <i class="bx bx-bell bx-tada"></i>
                    <span class="badge bg-danger rounded-pill">3</span>
                </button>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-end p-0"
                    aria-labelledby="page-header-notifications-dropdown">
                    <div class="p-3">
                        <div class="row align-items-center">
                            <div class="col">
                                <h6 class="m-0" key="t-notifications"> Notifications </h6>
                            </div>
                            <div class="col-auto">
                                <a href="#!" class="small" key="t-view-all"> View All</a>
                            </div>
                        </div>
                    </div>
                    <div data-simplebar style="max-height: 230px;">
                        <a href="javascript: void(0);" class="text-reset notification-item">
                            <div class="d-flex">
                                <div class="avatar-xs me-3">
                                    <span class="avatar-title bg-primary rounded-circle font-size-16">
                                        <i class="bx bx-cart"></i>
                                    </span>
                                </div>
                                <div class="flex-grow-1">
                                    <h6 class="mb-1" key="t-your-order">Your order is placed</h6>
                                    <div class="font-size-12 text-muted">
                                        <p class="mb-1" key="t-grammer">If several languages coalesce the
                                            grammar</p>
                                        <p class="mb-0"><i class="mdi mdi-clock-outline"></i> <span key="t-min-ago">3
                                                min ago</span></p>
                                    </div>
                                </div>
                            </div>
                        </a>
                        <a href="javascript: void(0);" class="text-reset notification-item">
                            <div class="d-flex">
                                <img src="{{ asset('/assets/images/users/avatar-3.jpg') }}"
                                    class="me-3 rounded-circle avatar-xs" alt="user-pic">
                                <div class="flex-grow-1">
                                    <h6 class="mb-1">James Lemire</h6>
                                    <div class="font-size-12 text-muted">
                                        <p class="mb-1" key="t-simplified">It will seem like simplified
                                            English.</p>
                                        <p class="mb-0"><i class="mdi mdi-clock-outline"></i> <span
                                                key="t-hours-ago">1 hours ago</span></p>
                                    </div>
                                </div>
                            </div>
                        </a>
                        <a href="javascript: void(0);" class="text-reset notification-item">
                            <div class="d-flex">
                                <div class="avatar-xs me-3">
                                    <span class="avatar-title bg-success rounded-circle font-size-16">
                                        <i class="bx bx-badge-check"></i>
                                    </span>
                                </div>
                                <div class="flex-grow-1">
                                    <h6 class="mb-1" key="t-shipped">Your item is shipped</h6>
                                    <div class="font-size-12 text-muted">
                                        <p class="mb-1" key="t-grammer">If several languages coalesce the
                                            grammar</p>
                                        <p class="mb-0"><i class="mdi mdi-clock-outline"></i> <span
                                                key="t-min-ago">3 min ago</span></p>
                                    </div>
                                </div>
                            </div>
                        </a>

                        <a href="javascript: void(0);" class="text-reset notification-item">
                            <div class="d-flex">
                                <img src="{{ asset('/assets/images/users/avatar-4.jpg') }}"
                                    class="me-3 rounded-circle avatar-xs" alt="user-pic">
                                <div class="flex-grow-1">
                                    <h6 class="mb-1">Salena Layfield</h6>
                                    <div class="font-size-12 text-muted">
                                        <p class="mb-1" key="t-occidental">As a skeptical Cambridge friend of
                                            mine occidental.</p>
                                        <p class="mb-0"><i class="mdi mdi-clock-outline"></i> <span
                                                key="t-hours-ago">1 hours ago</span></p>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="p-2 border-top d-grid">
                        <a class="btn btn-sm btn-link font-size-14 text-center" href="javascript:void(0)">
                            <i class="mdi mdi-arrow-right-circle me-1"></i> <span key="t-view-more">View More..</span>
                        </a>
                    </div>
                </div>
            </div>

            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item waves-effect" id="page-header-user-dropdown"
                    data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    @if (auth()->user()->avatar && \File::exists(public_path('/users/avatar/' . auth()->user()->avatar)))
                        <img class="rounded-circle header-profile-user"
                            src="{{ asset('/users/avatar/' . auth()->user()->avatar) }}" alt="Avatar">
                    @else
                        <img class="rounded-circle header-profile-user"
                            src="{{ asset('/assets/images/users/avatar-1.jpg') }}" alt="Avatar">
                    @endif
                    <span class="d-none d-xl-inline-block ms-1" key="t-henry">{{ auth()->user()->name }}</span>
                    <i class="mdi mdi-chevron-down d-none d-xl-inline-block"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-end">
                    <!-- item-->
                    <a class="dropdown-item" href="#"><i class="bx bx-user font-size-16 align-middle me-1"></i>
                        <span key="t-profile">Profile</span></a>
                    <a class="dropdown-item" href="#"><i
                            class="bx bx-wallet font-size-16 align-middle me-1"></i>
                        <span key="t-my-wallet">My Wallet</span></a>
                    <a class="dropdown-item d-block" href="#"><span
                            class="badge bg-success float-end">11</span><i
                            class="bx bx-wrench font-size-16 align-middle me-1"></i> <span
                            key="t-settings">Settings</span></a>
                    <a class="dropdown-item" href="#"><i
                            class="bx bx-lock-open font-size-16 align-middle me-1"></i>
                        <span key="t-lock-screen">Lock screen</span></a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item text-danger" href="{{ (auth()->guard('user')->check() && auth()->guard('user')->user()->role->slug == 'user' ? route('admin.user.logout') :  route('logout') ) }}"><i
                            class="bx bx-power-off font-size-16 align-middle me-1 text-danger"></i>
                        <span key="t-logout">{{ __('Logout') }}</span></a>
                </div>
            </div>
        </div>
    </div>
</header>

www/resources/views/layouts/admin/master.blade.php
<!doctype html>
<html lang="en">

<!-- Head Start -->
@include('layouts.admin.head')

<link href="{{ asset('/admin/css/custom.css') }}" rel="stylesheet" type="text/css" />
<!-- Head End -->

<body data-topbar="light" data-layout="horizontal">

    <!-- Begin page -->
    <div id="layout-wrapper">

        <!-- Header Start -->
        @include('layouts.admin.header')
        <!-- Header Start -->

        <div class="topnav">
            <div class="container-fluid">
                <nav class="navbar navbar-light navbar-expand-lg topnav-menu">

                    <div class="collapse navbar-collapse" id="topnav-menu-content">
                        <ul class="navbar-nav">

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle arrow-none" href="{{ route('admin.dashboard') }}"
                                    id="topnav-dashboard" role="button">
                                    <i class="bx bx-home-circle me-2"></i><span key="t-dashboards">Dashboards</span>
                                </a>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle arrow-none" href="javascript:;" id="topnav-pages"
                                    role="button">
                                    <i class="bx bxs-user me-2"></i><span key="t-apps">User Management</span>
                                    <div class="arrow-down"></div>
                                </a>
                                <div class="dropdown-menu" aria-labelledby="topnav-pages">
                                    <a href="{{ route('admin.user.index') }}" class="dropdown-item" key="t-chat">User
                                        List</a>
                                    <a href="{{ route('admin.user.createOrEdit') }}" class="dropdown-item"
                                        key="t-chat">Add User</a>
                                </div>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle arrow-none"
                                    href="{{ route('admin.location.index') }}" id="topnav-pages" role="button">
                                    <i class="fas fa-map-marker-alt me-2"></i><span key="t-apps">Location
                                        Management</span>
                                    <div class="arrow-down"></div>
                                </a>
                                <div class="dropdown-menu" aria-labelledby="topnav-pages">
                                    <a href="{{ route('admin.location.index') }}" class="dropdown-item"
                                        key="t-chat">Location List</a>
                                    <a href="{{ route('admin.location.edit') }}" class="dropdown-item"
                                        key="t-chat">Location Add</a>
                                </div>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle arrow-none" href="{{ route('admin.product.index') }}"
                                    id="topnav-pages" role="button">
                                    <i class='bx bxl-product-hunt me-2'></i><span key="t-apps">Products</span>
                                    <div class="arrow-down"></div>
                                </a>
                                <div class="dropdown-menu" aria-labelledby="topnav-pages">
                                    <a href="{{ route('admin.product.index') }}" class="dropdown-item"
                                        key="t-chat">Products List</a>
                                    <a href="{{ route('admin.product.createOrEdit') }}" class="dropdown-item"
                                        key="t-chat">Product Add</a>
                                </div>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle arrow-none"
                                    href="{{ route('admin.shipment.index') }}" id="topnav-pages" role="button">
                                    <i class='bx bxs-package me-2'></i><span key="t-apps">Shipments</span>
                                    <div class="arrow-down"></div>
                                </a>
                                <div class="dropdown-menu" aria-labelledby="topnav-pages">
                                    <a href="{{ route('admin.shipment.index') }}" class="dropdown-item"
                                        key="t-chat">Shipment List</a>
                                    <a href="{{ route('admin.shipment.cancelShipments') }}" class="dropdown-item"
                                        key="t-chat">Cancelled Shipment List</a>
                                </div>
                            </li>


                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle arrow-none" href="javascript:void(0);"
                                    id="topnav-pages" role="button">
                                    <i class='bx bxl-wallet me-2'></i><span key="t-apps">Payouts</span>
                                    <div class="arrow-down"></div>
                                </a>
                                <div class="dropdown-menu" aria-labelledby="topnav-pages">
                                    <a href="{{ route('admin.payout.index', 'draft') }}" class="dropdown-item"
                                        key="t-chat">Pending List</a>
                                    <a href="{{ route('admin.payout.index', 'completed') }}" class="dropdown-item"
                                        key="t-chat">Completed List</a>
                                </div>
                            </li>

                        </ul>
                    </div>
                </nav>
            </div>
        </div>

        <!-- ============================================================== -->
        <!-- Start right Content here -->
        <!-- ============================================================== -->
        <div class="main-content">
            <div class="page-content">
                @yield('main-content')
            </div>
        </div>
        <!-- end main content-->

        @include('layouts.admin.footer')

    </div>
    <!-- END layout-wrapper -->

    <!-- Right bar overlay-->
    <div class="rightbar-overlay"></div>

    @include('layouts.admin.scripts')

    <!-- Required datatable js -->
    <script src="{{ asset('/assets/libs/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('/assets/libs/datatables.net-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
    <!-- Buttons examples -->
    <script src="{{ asset('assets/libs/datatables.net-buttons/js/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('assets/libs/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js') }}"></script>
    <!-- Datatable init js -->
    <script src="{{ asset('/assets/js/pages/datatables.init.js') }}"></script>

    @stack('scripts')

    @livewireScripts
</body>

</html>

www/resources/views/layouts/admin/scripts.blade.php
<!-- JAVASCRIPT -->

<script src="{{ asset('/assets/libs/jquery/jquery.min.js') }}"></script>
<script src="{{ asset('/assets/libs/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('/assets/libs/metismenu/metisMenu.min.js') }}"></script>
<script src="{{ asset('/assets/libs/simplebar/simplebar.min.js') }}"></script>
<script src="{{ asset('/assets/libs/node-waves/waves.min.js') }}"></script>

<!-- App js -->
<script src="{{ asset('/assets/js/app.js') }}"></script>