www/routes/web.php
<?php

use App\Models\Shipment;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend.index');
});

Auth::routes();

// Route::get('/mail', function () {
//     $shipment = Shipment::find(16);
//     $mailType = 'vendor';
//     return view('email.free-quote-mail', compact('shipment', 'mailType'));
// });



Route::group(['namespace' => 'App\Http\Controllers'], function () {
    Route::get('/autologin', 'Auth\LoginController@autoLogin');

    Route::match(['get', 'post'], '/logout', 'Auth\LoginController@logout')->name('logout');

    Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['role:admin']], function () {
        Route::get('/dashboard', 'DashboardController@index')->middleware('permission:dashboard_access')->name('dashboard');

        /* User Management */
        Route::get('/users', 'UserController@index')->name('user.index');
        Route::get('/user/login/{id}', 'UserController@userLogin')->name('user.login');
        Route::get('/user/logout/', 'UserController@userLogout')->name('user.logout');
        Route::get('/user/create/{id?}', 'UserController@createOrEdit')->name('user.createOrEdit');
        Route::post('/user/store/{id?}', 'UserController@store')->name('user.store');
        Route::delete('/user/{id}/destroy', 'UserController@destroy')->name('user.delete');

        /* Location Management */
        Route::get('/location', 'LocationController@index')->name('location.index');
        Route::get('/location/edit/{id?}/', 'LocationController@edit')->name('location.edit');
        Route::post('/location/store/{id?}', 'LocationController@store')->name('location.store');
        Route::get('/location/show/{id}', 'LocationController@show')->name('location.show');
        Route::post('/location/assign-user/{id?}', 'LocationController@assignUser')->name('location.assign-user');
        Route::get('/location/export', 'LocationController@export')->name('location.export');
        Route::post('/location/import', 'LocationController@import')->name('location.import');

        /* Product Management */
        Route::get('/product', 'ProductController@index')->name('product.index');
        Route::get('/product/create/{id?}', 'ProductController@create')->name('product.createOrEdit');
        Route::get('/product/show/{id}', 'ProductController@show')->name('product.show');
        Route::get('/product/export', 'ProductController@export')->name('product.export');
        Route::post('/product/import', 'ProductController@import')->name('product.import');

        /* Shipments */
        Route::get('/shipments', 'ShipmentController@index')->name('shipment.index');
        Route::get('/shipment/show/{id}', 'ShipmentController@show')->name('shipment.show');
        Route::get('/shipment/change-status', 'ShipmentController@changeStatus')->name('shipment.change-status');
        Route::post('shipments/{id}/cancel', 'ShipmentController@cancelShipment')->name('shipment.cancel');
        Route::get('shipments/export', 'ShipmentController@export')->name('shipment.export');
        Route::get('shipments/cancel-shipments', 'ShipmentController@cancelShipmentIndex')->name('shipment.cancelShipments');

        /* Payouts */
        Route::get('/payouts/{status}', 'PayoutController@index')->name('payout.index');
        Route::get('/payouts/{id}/checkout', 'PayoutController@processCheckout')->name('payout.checkout');
        Route::get('/payouts/show/{id}', 'PayoutController@show')->name('payout.show');
    });

    Route::group(['prefix' => 'vendor', 'as' => 'vendor.', 'namespace' => 'Vendor', 'middleware' => ['role:vendor']], function () {
        Route::get('/dashboard', 'DashboardController@index')->middleware('permission:dashboard_access')->name('dashboard');
        Route::get('/no-locations', 'DashboardController@noLocations')->name('no-locations');

        // Trade-Ins Management
        Route::get('trade-ins', 'ShipmentController@tradeIns')->name('shipment.trade-ins');
        Route::get('trade-ins/show/{id}/', 'ShipmentController@tradeInShow')->name('shipment.trade-ins.show');

        // Shipment Management
        Route::get('shipments', 'ShipmentController@index')->name('shipment.index');
        Route::get('shipments/show/{id}/', 'ShipmentController@show')->name('shipment.show');
        Route::get('shipments/download-label/{id}', 'ShipmentController@downloadLabel')->name('shipment.download.label');
        Route::post('shipments/group-shipments', 'ShipmentController@groupShipments')->name('shipment.group-shipments');
        Route::post('shipments/{id}/cancel', 'ShipmentController@cancelShipment')->name('shipment.cancel');


        Route::get('/location/change/{id}', 'DashboardController@changeLocation')->name('location.change');

        Route::get('/shipments/approve-process/{id}', 'ShipmentController@approveProcess')->name('shipment.approveProcess');

        Route::get('/shipment-create', 'ShipmentController@createShipment')->name('shipment.create');
    });

    Route::group(['prefix' => 'user', 'as' => 'user.', 'namespace' => 'User', 'middleware' => ['auth']], function () {
        Route::get('/dashboard', 'DashboardController@index')->middleware('permission:dashboard_access')->name('dashboard');

        //Change Password
        Route::get('/password/change', 'DashboardController@changePasswordIndex')->name('password.change.index');
        Route::post('/change-password', 'DashboardController@changePassword')->name('password.change');

        // Shipment Management
        Route::get('/shipments', 'ShipmentController@index')->name('shipment.index');
        Route::get('/shipments/show/{id}/', 'ShipmentController@show')->name('shipment.show');
    });


    Route::group(['namespace' => 'Frontend'], function () {
        Route::get('/sell-your-device', 'SellDeviceController@index')->name('sell-your-device');
        Route::get('/shipment-process', 'SellDeviceController@shippingInformation')->name('shipment-process');
        Route::get('/shipment-review', 'SellDeviceController@shipmentReview')->name('shipment-review');
        Route::post('/confirm-location', 'SellDeviceController@confirmLocation')->name('confirm-location');
        Route::get('/ship-my-item', 'SellDeviceController@shipMyItemIndex')->name('ship-my-item');
        Route::get('/print-my-label', 'SellDeviceController@printMyLabelIndex')->name('print-my-label.index');
        Route::get('/print-my-label/download', 'SellDeviceController@printMyLabel')->name('print-my-label');
        Route::get('/cart', 'SellDeviceController@cart')->name('cart');
    });

    /* Contact Us */
    Route::get('contact-us', 'ContactUsController@index')->name('contact-us');
    Route::post('contact-us/store', 'ContactUsController@store')->name('contact-us.store');
    Route::post('buy-a-device-inquiry/store', 'ContactUsController@storeInquiry')->name('buy-a-device.inquiry.store');

    /** Request a free quote & Have a qustions*/
    Route::post('corporate-recycling/form/submit', 'ContactUsController@submitQuoteForm')->name('corporate-recycling.submit');
    Route::get('corporate-recycling/thank-you', 'ContactUsController@thankYouPage')->name('corporate-recycling.thankyou');

    /* Track Shipment */
    Route::get('/track-shipment', 'FrontendController@trackShipmentForm')->name('track-shipment');

    /* Sell Iphone */
    Route::get('/sell-iphone', 'FrontendController@sellIphone')->name('sell-iphone');
});

Route::group(['namespace' => 'App\Http\Livewire\Frontend'], function () {
    Route::get('/locations', Locations::class)->name('locations');
});

/*CMS Page */
Route::get('/{slug}', 'App\Http\Controllers\FrontendController@cmsPages')->name('cms-page');

Route::get('shipment-list', function () {
    return view('frontend.shipment-list');
})->name('shipment-list');

Route::get('shipment-detail/{id?}', function () {
    return view('frontend.shipment-detail');
})->name('shipment-detail');

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

www/app/Http/Controllers/Admin/LocationController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Locations\Distance;
use App\Models\Location;
use App\Models\User;
use Illuminate\Http\Request;

use App\Models\Shipment;
use Exception;
use Illuminate\Support\Facades\DB;

class LocationController extends Controller
{
    use Distance;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $locations = Location::with('users')->orderBy('id')->get();
        return view('admin.locations.index', compact('locations'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id = null)
    {
        $location = $id ? Location::findOrFail($id) : null;
        $users = User::all();
        return view('admin.locations.edit', compact('location', 'users'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $id = null)
    {
        $location = $id ? Location::findOrFail($id) : null;
        $this->validate($request, [
            'name' => 'required|max:30',
            'email' => 'required|email:rfc,strict,dns,spoof,filter',
            'address' => 'required|max:255',
            'address2' => 'max:255',
            'phone' => 'required|numeric|digits_between:0,9',
            'city' => 'required|string|max:30',
            'state' => 'required|string|max:30',
            'zip' => 'required|numeric|digits_between:0,9',
        ]);

        $data = $request->all();
        $location = Location::updateOrCreate(['id' => $location->id ?? null], $data);
        $location->users()->sync(($data['user_id'] ?? []));

        if ($location && !$id) {
            return redirect()->route('admin.location.index')->with('success', 'Location created successfully');
        } elseif ($location && $id) {
            return redirect()->route('admin.location.index')->with('success', 'Location updated successfully');
        } else {
            return redirect()->back()->with('error', 'Something went wrong')->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $location = Location::findOrFail($id);
        $shipments = $shipments = Shipment::where('location_id', $location->id)->orderBy('id', 'desc')->get();
        $users = User::all();

        return view('admin.locations.show', compact('location', 'shipments', 'users'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    /**
     * Assign users to location
     */
    public function assignUser(Request $request, $id)
    {
        $location = Location::findOrFail($id);
        $location->users()->sync($request->user_id);
        return redirect()->back()->with('success', 'User assigned successfully');
    }
    /**
     * import all the location
     */
    public function import(Request $request)
    {
        ini_set('max_execution_time', 300); // 5 minutes

        $this->validate($request, [
            'csv' => 'required|mimes:csv,txt'
        ]);

        // check file exists and it's readable
        if (!file_exists($request->file('csv')) || !is_readable($request->file('csv'))) {
            return redirect()->back()->with('error', 'Unable to read file');
        }

        $logMessages = [];
        if (($handle = fopen($request->csv, 'r')) !== false) {
            $counter = 1;
            while (($row = fgetcsv($handle, 1000, ',')) !== false) {
                // skip if row is empty
                if (empty(array_filter($row))) {
                    $counter++;
                    continue;
                }

                // set the header row as key for the array
                if (!isset($header)) {
                    $header = $row;
                    $validateColumn = array_diff($this->getLocationCsvHeader(), $header);
                    if (!empty($validateColumn)) {
                        return redirect()->back()->with('error', \implode(',', $validateColumn) . ' columns does not exists in csv file');
                    }
                    $counter++;
                    continue;
                }

                $location = array_combine($header, $row);
                $notEmptyFields = [];

                if ($this->isEmpty($location['name'])) {
                    $notEmptyFields[] = 'name';
                }
                if ($this->isEmpty($location['address'])) {
                    $notEmptyFields[] = 'address';
                }
                if ($this->isEmpty($location['city'])) {
                    $notEmptyFields[] = 'city';
                }
                if ($this->isEmpty($location['state'])) {
                    $notEmptyFields[] = 'state';
                }
                if ($this->isEmpty($location['zip'])) {
                    $notEmptyFields[] = 'zip';
                }
                if ($this->isEmpty($location['email'])) {
                    $notEmptyFields[] = 'email';
                }
                if ($this->isEmpty($location['phone'])) {
                    $notEmptyFields[] = 'phone';
                }
                if ($this->isEmpty($location['active'])) {
                    $notEmptyFields[] = 'active';
                }
             
                if ($this->isEmpty($location['geo_lng']) && $this->isEmpty($location['geo_lat'])) {
                    $address = $location['address'] . (!empty($location['address2']) ? ', ' . $location['address2'] . ', ' : ', ') . $location['city'] . ', ' . $location['state'] . ' ' . $location['zip'] . ', ' . 'USA';
                    if ($this->getLatLong($address)) {
                        $location['geo_lat'] = $this->lat;
                        $location['geo_lng'] = $this->lng;
                    }
                }

                if (!empty($notEmptyFields)) {
                    $logMessages['validation'][] = $counter . ' Location has empty fields ' . implode(',', $notEmptyFields);
                    $counter++;
                    continue;
                }
                DB::beginTransaction();
                try {
                    Location::create($location);
                    DB::commit();
                    $logMessages['success'][] = $counter . ' Location created';
                } catch (Exception $e) {
                    DB::rollBack();
                    $logMessages['error'][] = $counter . ' Location has error.';
                }
                $counter++;
                continue;
            }
        }
        fclose($handle);

        return back()->with('importLog', $logMessages);
    }

    public function isEmpty($data)
    {
        if ($data == null || $data == '' || $data == 'null' || $data == 'NULL' || $data == 'Null' || $data == '-') {
            return true;
        }
        return false;
    }

    /**
     * Export the location
     */
    public function export()
    {
        $fileName = 'Location_' . date("Y-m-d") . '.csv';
        $locations = Location::select('name', 'address', 'address2', 'city', 'state', 'zip', 'email', 'phone', 'external_location_id', 'active', 'hours_of_opration', 'geo_lat', 'geo_lng')->get();

        $columns = $this->getLocationCsvHeader();
        $callback = function () use ($columns, $locations) {
            $file = fopen('php://output', 'w');
            fputcsv($file, $columns);

            foreach ($locations->toArray() as $key => $row) {
                fputcsv($file, $row);
            }

            fclose($file);
        };
        return response()->stream($callback, 200, ["Content-type" => "text/csv", "Content-Disposition" => "attachment; filename=$fileName", "Pragma" => "no-cache", "Cache-Control" => "must-revalidate, post-check=0, pre-check=0", "Expires" => "0"]);
    }

    public function getLocationCsvHeader()
    {
        return ['name', 'address', 'address2', 'city', 'state', 'zip', 'email', 'phone', 'external_location_id', 'active', 'hours_of_opration', 'geo_lat', 'geo_lng'];
    }
}

www/resources/views/admin/locations/index.blade.php
@extends('layouts.admin.master')
@section('title', 'GIZMOGUL || Locations List')
@push('styles')
    <!-- DataTables -->
    <link href="{{ asset('/assets/libs/datatables.net-bs4/css/dataTables.bootstrap4.min.css') }}" rel="stylesheet"
        type="text/css" />
    <link href="{{ asset('/assets/libs/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css') }}" rel="stylesheet"
        type="text/css" />

    <!-- Responsive datatable examples -->
    <link href="{{ asset('/assets/libs/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css') }}" rel="stylesheet"
        type="text/css" />
@endpush
@section('main-content')
    <div class="container-fluid">
        <!-- start page title -->
        <div class="row">
            <div class="col-12">
                <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                    <h4 class="mb-sm-0 font-size-18">Users Location List</h4>
                </div>
            </div>
        </div>
        <!-- end page title -->

        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <!-- Export Csv Button -->
                            <div class="float-right mb-3 button-flex">
                                <a href="{{ route('admin.location.export') }}" class="btn btn-primary">
                                    <i class="bx bx-download me-2"></i>Export CSV
                                </a>
                                {{-- <a href="javascript:;" class="btn btn-primary waves-effect waves-light">
                                    <i class="bx bx-download me-2"></i>Export CSV
                                </a> --}}
                            </div>

                            <!-- Import Csv Button -->
                            <div class="float-right mb-3 button-flex">
                                <button role="button" class="btn btn-primary waves-effect waves-light"
                                    data-bs-toggle="modal" data-bs-target=".bs-import-csv-modal">
                                    <i class="bx bx-upload me-2"></i>Import CSV
                                </button>
                                <div class="modal fade bs-import-csv-modal" tabindex="-1" role="dialog"
                                    aria-hidden="true">
                                    <div class="modal-dialog modal-dialog-centered">
                                        <div class="modal-content">
                                            <form id="csv-upload-form" method="POST"
                                                action="{{ route('admin.location.import') }}" enctype="multipart/form-data">
                                                @csrf
                                                <div class="modal-header">
                                                    <h5 class="modal-title">Select CSV File</h5>
                                                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                        aria-label="Close"></button>
                                                </div>
                                                <div class="modal-body">
                                                    <div class="mb-3">
                                                        <input type="file" class="form-control" name="csv"
                                                            id="csv-file">
                                                        @error('csv')
                                                            <span class="invalid-feedback" role="alert">
                                                                <strong>{{ $message }}</strong>
                                                            </span>
                                                        @enderror
                                                        <span id="csv_file_error"></span>
                                                        <span id="csv_file_type"></span>
                                                    </div>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary"
                                                        data-bs-dismiss="modal">Close</button>
                                                    <button type="submit" id="sbumit-csv"
                                                        class="btn btn-primary">Import</button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="table-responsive">
                            <table class="table align-middle table-nowrap table-hover table table-bordered data-table">
                                <thead class="table-light">
                                    <tr>
                                        <th scope="col">Name</th>
                                        <th scope="col">Email</th>
                                        <th scope="col">Phone</th>
                                        <th scope="col">Address</th>
                                        <th scope="col">City</th>
                                        <th scope="col">State</th>
                                        <th scope="col">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($locations as $key => $location)
                                        <tr>
                                            <td>
                                                <div class="location-show-link"><a
                                                        href="{{ route('admin.location.show', $location->id) }}">{{ $location->name }}</a>
                                                </div>
                                            </td>
                                            <td>{{ $location->email }}</td>
                                            <td>{{ $location->phone }}</td>
                                            <td>{{ Str::limit($location->address, 35) }}</td>
                                            <td>{{ $location->city }}</td>
                                            <td>{{ $location->state }}</td>
                                            <td>
                                                <div class="dropdown">
                                                    <a href="#" class="dropdown-toggle card-drop"
                                                        data-bs-toggle="dropdown" aria-expanded="false">
                                                        <i class="mdi mdi-dots-horizontal font-size-18"></i>
                                                    </a>
                                                    <div class="dropdown-menu dropdown-menu-end">
                                                        <a class="dropdown-item"
                                                            href="{{ route('admin.location.edit', $location->id) }}">Edit</a>
                                                        <a class="dropdown-item"
                                                            href="{{ route('admin.location.show', $location->id) }}">View</a>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @if (session()->has('importLog'))
        <div class="modal" tabindex="-1" role="dialog" id="myModal">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Log Import CSV.</h5>
                        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>

                    <div class="modal-body log-message">
                        @foreach (session()->get('importLog') as $key => $value)
                                <h3> {{$key}} </h3>
                                <ul>
                                    @foreach ($value as $t => $v)
                                        <h5> {{ ucwords($v) }} </h4>
                                    @endforeach
                                </ul>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    @endif
@endsection
@push('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.5/jquery.validate.min.js"></script>
    <script type="text/javascript">
        $(function() {
            @if (session()->has('importLog'))
                $(window).on('load', function() {
                    $('#myModal').modal('show');
                });
            @endif

            $('.data-table').DataTable({
                "columnDefs": [{
                    "orderable": false,
                    "targets": [6]
                }, {
                    "targets": [0, 1, 2, 3, 4, 5, 6],
                    "className": "text-center",
                }],
            });

            $("#csv-upload-form").validate({
                errorClass: "invalid-feedback",
                validClass: "valid success-alert",
                rules: {
                    csv: {
                        required: true,
                    },
                },
                messages: {
                    csv: {
                        required: "Please select CSV file",
                    }
                }
            });

            $("#csv-file").change(function() {
                $("#csv_file_error").html("");
                $("#csv_file_type").html("");
                var file_size = $('#csv-file')[0].files[0].size;
                var fileType = $('#csv-file')[0].files[0].type;
                var validTypes = ['text/csv'];
                if (false == validTypes.includes(fileType)) {
                    $("#csv_file_type").html(
                        "<p style='color:#FF0000'>Please select valid file type - CSV</p>"
                    );
                    $('#sbumit-csv').prop('disabled', true);
                } else if (parseInt(file_size) >= 3000000) {
                    $("#csv_file_error").html(
                        "<p style='color:#FF0000'>Please upload file size is less than 3MB</p>");
                    $('#sbumit-csv').prop('disabled', true);
                } else if (parseInt(file_size) <= 3000000) {
                    $('#sbumit-csv').prop('disabled', false);
                } else {
                    $('#sbumit-csv').prop('disabled', false);
                }
            });
        });
    </script>
@endpush